export const DEFAULT_URL_IMG = "https://i.ibb.co/JvKSP4t/default.png";

export const MIN_LENGTH_PASSWORD = 8;

export const MIN_LENGTH_NAME = 10;

export const CODE_SEND = `Verification code was successfully sent to the mail.`;

export const RECORD_DELETED = `Record has been deleted.`;

export const DEFAULT_WEATHER = "Unknown";

export const TYPE_TOKEN = "Bearer";

export enum ROLES {
  USER = "USER",
  ADMIN = "ADMIN",
  GUIDE = "GUIDE",
  SUPER_ADMIN = "SUPER_ADMIN",
}

export enum ERROR {
  INCORRECT_INPUT = "INCORRECT_INPUT",
  USER_EXIST = "USER_EXIST",
  PASSWORD_REQUIREMENTS = "PASSWORD_REQUIREMENTS",
  NO_PERSONAL_DATA = "NO_PERSONAL_DATA",
  SIMPLE_PASSWORD = "SIMPLE_PASSWORD",
  INCORRECT_EMAIL = "INCORRECT_EMAIL",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  INCORRECT_PASSWORD = "INCORRECT_PASSWORD",
  USERNAME_NOT_FOUND = "USERNAME_NOT_FOUND",
  FILE_NOT_IMAGE = "FILE_NOT_IMAGE",
  INCORRECT_NAME = "INCORRECT_NAME",
  INCORRECT_CODE = "INCORRECT_CODE",
  NOT_AUTHORIZED = "NOT_AUTHORIZED",
  NO_ACCESS = "NO_ACCESS",
  GUIDE_NOT_FOUND = "GUIDE_NOT_FOUND",
  TAG_NOT_FOUND = "TAG_NOT_FOUND",
  SIGHT_NOT_FOUND = "SIGHT_NOT_FOUND",
  CITY_NOT_FOUND = "CITY_NOT_FOUND",
  RECOMMEND_NOT_FOUND = "RECOMMEND_NOT_FOUND",
  INVALID_TYPE_TOKEN = "INVALID_TYPE_TOKEN",
  LONG_NAME = "LONG_NAME",
  SHORT_PASSWORD = "SHORT_PASSWORD",
  RECOMMEND_FOUND = "RECOMMEND_FOUND",
  USER_IS_BANNED = "USER_IS_BANNED",
  USER_IS_UNBANNED = "USER_IS_UNBANNED",
  USER_IS_ALREADY_GUIDE = "USER_IS_ALREADY_GUIDE",
  GUIDE_REQUEST_ALREADY_EXISTS = "GUIDE_REQUEST_ALREADY_EXISTS",
  GUIDE_REQUEST_NOT_FOUND = "GUIDE_REQUEST_NOT_FOUND",
  USER_IS_ALREADY_ADMIN = "USER_IS_ALREADY_ADMIN",
  USER_IS_NOT_ADMIN = "USER_IS_NOT_ADMIN",
  USER_IS_SUPER_ADMIN = "USER_IS_SUPER_ADMIN",
}

export enum Locales {
  RU = "ru",
  EN = "en",
}

export enum GUIDES_REQUEST_STATUS {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}

export enum EMAIL_SUBJECTS {
  VERIFICATION_CODE = "Verification Code Vista go",
  GUIDE_REQUEST = "Guide Request Vista go",
  REJECT_GUIDE_REQUEST = "Reject Guide Request Vista go",
  ACCEPT_GUIDE_REQUEST = "Accept Guide Request Vista go",
  REQUEST_FOR_ADMIN = "Request for admin Vista go",
}
