"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    return queryInterface.bulkInsert("tags", [
      {
        id: 1,
        name: "Landmark",
        SightId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        name: "Architecture",
        SightId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        name: "History",
        SightId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        name: "Religion",
        SightId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        name: "Empire",
        SightId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        name: "History",
        SightId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 7,
        name: "Checkpoint",
        SightId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 8,
        name: "Berlin Wall",
        SightId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 9,
        name: "History",
        SightId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 10,
        name: "Column",
        SightId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 11,
        name: "Victory",
        SightId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 12,
        name: "History",
        SightId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 13,
        name: "Fish",
        SightId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 14,
        name: "Market",
        SightId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 15,
        name: "Meal",
        SightId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 16,
        name: "Sea",
        SightId: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 17,
        name: "Museum",
        SightId: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 18,
        name: "Zoo",
        SightId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 19,
        name: "Animals",
        SightId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 20,
        name: "Science",
        SightId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 21,
        name: "Life",
        SightId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 22,
        name: "Museum",
        SightId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 23,
        name: "Science",
        SightId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 24,
        name: "Hall",
        SightId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 25,
        name: "Administration",
        SightId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 26,
        name: "History",
        SightId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 27,
        name: "Religion",
        SightId: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 28,
        name: "Architecture",
        SightId: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 29,
        name: "Gates",
        SightId: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 30,
        name: "Architecture",
        SightId: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 31,
        name: "History",
        SightId: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 32,
        name: "Library",
        SightId: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 33,
        name: "Architecture",
        SightId: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 34,
        name: "Science",
        SightId: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 35,
        name: "Castle",
        SightId: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 36,
        name: "The Middle Ages",
        SightId: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 37,
        name: "History",
        SightId: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 38,
        name: "Religion",
        SightId: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 39,
        name: "Architecture",
        SightId: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 40,
        name: "History",
        SightId: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 41,
        name: "Religion",
        SightId: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 42,
        name: "Museum",
        SightId: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 43,
        name: "History",
        SightId: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 44,
        name: "Park",
        SightId: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 45,
        name: "Nature",
        SightId: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 46,
        name: "Religion",
        SightId: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 47,
        name: "Architecture",
        SightId: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 48,
        name: "History",
        SightId: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 49,
        name: "Winery",
        SightId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 50,
        name: "Architecture",
        SightId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 51,
        name: "Wine",
        SightId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 52,
        name: "Square",
        SightId: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 53,
        name: "Architecture",
        SightId: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 54,
        name: "History",
        SightId: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 55,
        name: "Beauty",
        SightId: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 56,
        name: "Architecture",
        SightId: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 57,
        name: "Fortress",
        SightId: 21,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 58,
        name: "Architecture",
        SightId: 21,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 59,
        name: "History",
        SightId: 21,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 60,
        name: "Square",
        SightId: 22,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 61,
        name: "Architecture",
        SightId: 22,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 62,
        name: "Park",
        SightId: 23,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 63,
        name: "Architecture",
        SightId: 23,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 64,
        name: "Nature",
        SightId: 23,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 65,
        name: "Religion",
        SightId: 24,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 66,
        name: "Architecture",
        SightId: 24,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    return queryInterface.bulkDelete("tags", null, {});
  },
};
