import { QueryInterface } from "sequelize";

export default {
  up: async (queryInterface: QueryInterface) => {
    const now = new Date();
    const passwordHash =
      "$2b$05$PGag7sTWGUYok5EGMDMMT.QLrD6MfOtBcq1C4Mysc9nZ4dTGyoSU6"; // Str0ngP@ss

    const users = [
      {
        name: "Admin",
        email: "adminus@gmail.com",
        password: passwordHash,
        image: "https://i.ibb.co/JvKSP4t/default.png",
        role: "ADMIN",
        isBanned: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        name: "User",
        email: "user@gmail.com",
        password: passwordHash,
        image: "https://i.ibb.co/JvKSP4t/default.png",
        role: "USER",
        isBanned: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        name: "Andrey Medvedik",
        email: "andrey@example.com",
        password: passwordHash,
        image: "https://i.ibb.co/Nd9MBTwd/andr.png",
        role: "GUIDE",
        isBanned: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        name: "Stepan Naymkin",
        email: "stepan@example.com",
        password: passwordHash,
        image: "https://i.ibb.co/rKfg9BX0/stepank.png",
        role: "GUIDE",
        isBanned: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        name: "Anna Kravchenko",
        email: "anna@example.com",
        password: passwordHash,
        image: "https://i.ibb.co/7Jqt17cm/kravchenko.png",
        role: "GUIDE",
        isBanned: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        name: "Olga Levchenko",
        email: "olga@example.com",
        password: passwordHash,
        image: "https://i.ibb.co/hxD5KqZD/levchenko.png",
        role: "GUIDE",
        isBanned: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        name: "Maria Schmidt",
        email: "maria@example.com",
        password: passwordHash,
        image: "https://i.ibb.co/Rk9B1pMM/schmidt.png",
        role: "GUIDE",
        isBanned: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        name: "Jan Mueller",
        email: "jan@example.com",
        password: passwordHash,
        image: "https://i.ibb.co/YTK1PnZM/mueller.png",
        role: "GUIDE",
        isBanned: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        name: "Lena Wagner",
        email: "lena@example.com",
        password: passwordHash,
        image: "https://i.ibb.co/gHRCTN6/wagner.png",
        role: "GUIDE",
        isBanned: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        name: "Max Schulz",
        email: "max@example.com",
        password: passwordHash,
        image: "https://i.ibb.co/cc9f3X4H/schulz.png",
        role: "GUIDE",
        isBanned: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        name: "Mark Arutyunyan",
        email: "mark@example.com",
        password: passwordHash,
        image: "https://i.ibb.co/q35kQzyd/arutyunyan.png",
        role: "GUIDE",
        isBanned: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        name: "Artur Avetisyan",
        email: "artur@example.com",
        password: passwordHash,
        image: "https://i.ibb.co/Tx7KHtk2/avetisyan.png",
        role: "GUIDE",
        isBanned: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        name: "Narek Arutyunyan",
        email: "narek@example.com",
        password: passwordHash,
        image: "https://i.ibb.co/tfpQnyB/arutyunyan.png",
        role: "GUIDE",
        isBanned: false,
        createdAt: now,
        updatedAt: now,
      },
      {
        name: "Angela Abramyan",
        email: "angela@example.com",
        password: passwordHash,
        image: "https://i.ibb.co/Kcqv7r2S/abramyan.png",
        role: "GUIDE",
        isBanned: false,
        createdAt: now,
        updatedAt: now,
      },
    ];

    await queryInterface.bulkInsert("users", users);
  },

  down: async (queryInterface: QueryInterface) => {
    return queryInterface.bulkDelete("users", null, {});
  },
};
