import { QueryInterface } from "sequelize";

export default {
  up: async (queryInterface: QueryInterface) => {
    const sightTags = [
      { SightId: 1, TagId: 1 },
      { SightId: 1, TagId: 2 },
      { SightId: 1, TagId: 3 },
      { SightId: 2, TagId: 4 },
      { SightId: 2, TagId: 5 },
      { SightId: 3, TagId: 6 },
      { SightId: 3, TagId: 7 },
      { SightId: 3, TagId: 3 },
      { SightId: 4, TagId: 8 },
      { SightId: 4, TagId: 9 },
      { SightId: 4, TagId: 3 },
      { SightId: 5, TagId: 10 },
      { SightId: 5, TagId: 11 },
      { SightId: 5, TagId: 12 },
      { SightId: 6, TagId: 13 },
      { SightId: 6, TagId: 14 },
      { SightId: 7, TagId: 15 },
      { SightId: 7, TagId: 16 },
      { SightId: 7, TagId: 17 },
      { SightId: 8, TagId: 18 },
      { SightId: 8, TagId: 14 },
      { SightId: 8, TagId: 17 },
      { SightId: 9, TagId: 19 },
      { SightId: 9, TagId: 19 },
      { SightId: 9, TagId: 3 },
      { SightId: 10, TagId: 4 },
      { SightId: 10, TagId: 2 },
      { SightId: 11, TagId: 21 },
      { SightId: 11, TagId: 2 },
      { SightId: 11, TagId: 3 },
      { SightId: 12, TagId: 22 },
      { SightId: 12, TagId: 2 },
      { SightId: 12, TagId: 17 },
      { SightId: 13, TagId: 23 },
      { SightId: 13, TagId: 24 },
      { SightId: 13, TagId: 3 },
      { SightId: 14, TagId: 4 },
      { SightId: 14, TagId: 2 },
      { SightId: 14, TagId: 3 },
      { SightId: 15, TagId: 4 },
      { SightId: 15, TagId: 14 },
      { SightId: 15, TagId: 3 },
      { SightId: 16, TagId: 25 },
      { SightId: 16, TagId: 26 },
      { SightId: 17, TagId: 4 },
      { SightId: 17, TagId: 2 },
      { SightId: 17, TagId: 3 },
      { SightId: 18, TagId: 27 },
      { SightId: 18, TagId: 2 },
      { SightId: 18, TagId: 28 },
      { SightId: 19, TagId: 29 },
      { SightId: 19, TagId: 2 },
      { SightId: 19, TagId: 3 },
      { SightId: 20, TagId: 30 },
      { SightId: 20, TagId: 2 },
      { SightId: 21, TagId: 31 },
      { SightId: 21, TagId: 2 },
      { SightId: 21, TagId: 3 },
      { SightId: 22, TagId: 29 },
      { SightId: 22, TagId: 2 },
      { SightId: 23, TagId: 25 },
      { SightId: 23, TagId: 2 },
      { SightId: 23, TagId: 26 },
      { SightId: 24, TagId: 4 },
      { SightId: 24, TagId: 2 },
    ];

    const sightTagsWithTimestamps = sightTags.map((tag) => ({
      ...tag,
      createdAt: new Date(),
      updatedAt: new Date(),
    }));

    await queryInterface.bulkInsert("sighttags", sightTagsWithTimestamps);
  },

  down: async (queryInterface: QueryInterface) => {
    await queryInterface.bulkDelete("sighttags", null, {});
  },
};
